sonar.projectKey=OliverGongCR
sonar.projectName=OliverGongCR
sonar.sources=apps/web/app,apps/export-worker/src,apps/server/src/main,apps/ai-worker/src/main
sonar.tests=apps/export-worker/src,apps/server/src/test
sonar.test.inclusions=**/*.test.ts,**/src/test/**
sonar.javascript.lcov.reportPaths=apps/export-worker/coverage/lcov.info,apps/web/coverage/lcov.info
sonar.coverage.jacoco.xmlReportPaths=apps/server/target/site/jacoco/jacoco.xml,apps/ai-worker/target/site/jacoco/jacoco.xml
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/target/**
