name: 功能建议
description: 提议产品或工程改进
title: '[Feature] '
labels: [enhancement]
body:
  - type: textarea
    id: value
    attributes: { label: 用户价值 }
    validations: { required: true }
  - type: textarea
    id: acceptance
    attributes: { label: 验收标准 }
    validations: { required: true }
